import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Forerunner</title>
        <meta name="description" content="Generated by dev papa" />
        <link rel="icon" href="/forerunner.svg" />
      </Head>
    </div>
  );
}
