import Head from "next/head";
import Image from "next/image";
import OurPerspectives from "../components/OurPerspectives";
import Card1 from "../components/cards/Card1";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Forerunner</title>
        <meta name="description" content="Generated by dev papa" />
        <link rel="icon" href="/forerunner.svg" />
      </Head>
      <OurPerspectives />
      <Card1 />
    </div>
  );
}
